version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: ffffookorj/foodgram_backend
    env_file: .env
    volumes:
      - ../frontend/build/static/:/backend_static/
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: ffffookorj/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: nginx:1.19.3
    ports:
      - "8080:80"
    volumes:
      - media:/usr/share/nginx/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
