# Generated by Django 3.2 on 2023-07-26 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'избранный рецепт',
                'verbose_name_plural': 'избранные рецепты',
                'default_related_name': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название ингридиета', max_length=200, verbose_name='имя')),
                ('measurement_unit', models.CharField(help_text='единица изменения (например грамм)', max_length=200, verbose_name='ед. изм.')),
            ],
            options={
                'verbose_name': 'ингридиент',
                'verbose_name_plural': 'ингридиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название рецепта', max_length=200, verbose_name='имя')),
                ('text', models.TextField(help_text='пошаговое описание процесса приготовления', verbose_name='описание')),
                ('cooking_time', models.PositiveIntegerField(help_text='укажите время приготовления (в минутах)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='время приготовления')),
                ('image', models.ImageField(blank=True, help_text='добавьте картинку к рецепту', upload_to='recipes/', verbose_name='картинка')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngrideint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, help_text='количество ингридиентов для рецепта', validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество ингридиентов')),
            ],
            options={
                'ordering': ['-amount'],
                'default_related_name': 'ingrideints',
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipes', models.ManyToManyField(help_text='рецепты в списке покупок', to='food.Recipe', verbose_name='рецепты')),
            ],
            options={
                'verbose_name': 'список покупок',
                'verbose_name_plural': 'списки покупок',
            },
        ),
    ]
