# Generated by Django 3.2 on 2023-07-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngrideints',
            new_name='RecipeIngrideint',
        ),
    ]
