# Generated by Django 3.2 on 2023-07-29 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingrideint',
            options={'ordering': ['-amount']},
        ),
        migrations.AlterField(
            model_name='recipeingrideint',
            name='ingredient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='recipes',
                to='food.ingredient',
                verbose_name='ингридиент',
            ),
        ),
    ]
