# Generated by Django 3.2 on 2023-07-23 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_recipeingrideints_recipeingrideint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingrideint',
            options={'default_related_name': 'ingrideints', 'ordering': ['-amount']},
        ),
        migrations.AlterField(
            model_name='recipeingrideint',
            name='amount',
            field=models.PositiveIntegerField(default=1, help_text='количество ингридиентов для рецепта', validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество ингридиентов'),
        ),
        migrations.AlterField(
            model_name='recipeingrideint',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrideints', to='food.ingredient', verbose_name='ингридиент'),
        ),
        migrations.AlterField(
            model_name='recipeingrideint',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrideints', to='food.recipe', verbose_name='рецепт'),
        ),
        migrations.AddConstraint(
            model_name='recipeingrideint',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
    ]
