# Generated by Django 3.2 on 2023-07-29 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0003_auto_20230729_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={
                'default_related_name': 'shopping_list',
                'verbose_name': 'список покупок',
                'verbose_name_plural': 'списки покупок',
            },
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='recipes',
            field=models.ManyToManyField(
                help_text='рецепты в списке покупок',
                related_name='shopping_list',
                to='food.Recipe',
                verbose_name='рецепты',
            ),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(
                help_text='пользователь, владелец списка покупок',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='shopping_list',
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь',
            ),
        ),
    ]
