# Generated by Django 3.2 on 2023-07-24 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0003_auto_20230723_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={
                'verbose_name': 'ингридиент',
                'verbose_name_plural': 'ингридиенты',
            },
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
            },
        ),
    ]
