# Generated by Django 3.2 on 2023-07-24 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0004_auto_20230724_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={
                'verbose_name': 'избранный рецепт',
                'verbose_name_plural': 'избранные рецепты',
            },
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={
                'verbose_name': 'список покупок',
                'verbose_name_plural': 'списки покупок',
            },
        ),
    ]
