# Generated by Django 3.2 on 2023-07-29 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0004_auto_20230729_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='recipes',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='recipe',
            field=models.ForeignKey(
                default=1,
                help_text='рецепты в списке покупок',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='shopping_list',
                to='food.recipe',
                verbose_name='рецепты',
            ),
            preserve_default=False,
        ),
    ]
