# Generated by Django 3.2 on 2023-07-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0005_auto_20230729_1622'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(
                fields=('user', 'recipe'), name='unique_user_recipe'
            ),
        ),
    ]
