# Generated by Django 3.2 on 2023-07-25 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0005_auto_20230724_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={
                'default_related_name': 'favorites',
                'verbose_name': 'избранный рецепт',
                'verbose_name_plural': 'избранные рецепты',
            },
        ),
        migrations.AlterField(
            model_name='favoriterecipe',
            name='recipes',
            field=models.ManyToManyField(
                help_text='отмеченные рецепты',
                related_name='favorites',
                to='food.Recipe',
                verbose_name='рецепты',
            ),
        ),
        migrations.AlterField(
            model_name='favoriterecipe',
            name='user',
            field=models.ForeignKey(
                help_text='пользователь, который отметил рецепт',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='favorites',
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь',
            ),
        ),
    ]
