# Generated by Django 3.2 on 2023-07-31 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20230731_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriterecipe',
            name='recipes',
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='recipe',
            field=models.ForeignKey(default=1, help_text='отмеченные рецепты', on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='food.recipe', verbose_name='рецепты'),
            preserve_default=False,
        ),
    ]
