# Generated by Django 3.2 on 2023-07-26 19:25

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'подписки',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название рецепта', max_length=200, verbose_name='имя')),
                ('slug', models.SlugField(help_text='идентификатор тэга', max_length=200, unique=True, verbose_name='слаг')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', help_text='цвет тега', image_field=None, max_length=18, samples=None, verbose_name='цвет')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'ordering': ['slug'],
            },
        ),
    ]
