# Generated by Django 3.2 on 2023-07-23 12:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(
                default='#FFFFFF',
                help_text='цвет тега',
                image_field=None,
                max_length=18,
                samples=None,
            ),
        ),
    ]
