# Generated by Django 3.2 on 2023-07-31 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gram', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(
                help_text='на кого подписался пользователь',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscriber',
                to=settings.AUTH_USER_MODEL,
                verbose_name='автор',
            ),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(
                help_text='пользователь, который подписался',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscribed',
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь',
            ),
        ),
    ]
