# Generated by Django 3.2 on 2023-07-23 14:27

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gram', '0002_alter_tag_color'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(
                fields=('user', 'author'), name='unique_user_author'
            ),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(
                check=models.Q(user=django.db.models.expressions.F('author')),
                name='no_selt_sub',
            ),
        ),
    ]
