# Generated by Django 3.2 on 2023-07-23 14:29

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_auto_20230723_1427'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='no_selt_sub',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='no_selt_sub'),
        ),
    ]
