# Generated by Django 3.2 on 2023-07-24 18:30

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gram', '0005_alter_subscription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'подписки',
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(
                default='#FFFFFF',
                help_text='цвет тега',
                image_field=None,
                max_length=18,
                samples=None,
                verbose_name='цвет',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(
                help_text='идентификатор тэга',
                max_length=200,
                unique=True,
                verbose_name='слаг',
            ),
        ),
    ]
