# Generated by Django 3.2 on 2023-08-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favoriterecipe',
            constraint=models.UniqueConstraint(
                fields=('user', 'recipe'), name='unique_user_recipe_favorite'
            ),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(
                fields=('user', 'recipe'),
                name='unique_user_recipe_shopping_list',
            ),
        ),
    ]
