# Generated by Django 3.2 on 2023-08-05 10:26

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingrideint',
            options={'ordering': ['-amount'], 'verbose_name': 'ингредиент рецепта', 'verbose_name_plural': 'ингредиенты рецептов'},
        ),
        migrations.AlterField(
            model_name='recipeingrideint',
            name='ingredient',
            field=models.ForeignKey(help_text='ингредиет рецепта', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipe.ingredient', verbose_name='ингридиент'),
        ),
        migrations.AlterField(
            model_name='recipeingrideint',
            name='recipe',
            field=models.ForeignKey(help_text='рецепт, к которому относится ингредиент', on_delete=django.db.models.deletion.CASCADE, related_name='ingrideints', to='recipe.recipe', verbose_name='рецепт'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='цвет тега', image_field=None, max_length=7, samples=None, verbose_name='цвет'),
        ),
    ]
