# Generated by Django 3.2 on 2023-08-06 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('recipe', '0003_alter_recipeingrideint_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={
                'ordering': ('slug',),
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
    ]
