# Generated by Django 3.2 on 2023-08-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20230805_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',), 'verbose_name': 'ингридиент', 'verbose_name_plural': 'ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': 'рецепт', 'verbose_name_plural': 'рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingrideint',
            options={'ordering': ('-amount',), 'verbose_name': 'ингредиент рецепта', 'verbose_name_plural': 'ингредиенты рецептов'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('user',), 'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
    ]
