# Generated by Django 3.2 on 2023-08-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                help_text='электронная почта пользователя',
                max_length=254,
                unique=True,
                verbose_name='эл. почта',
            ),
        ),
    ]
